source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

use_frameworks!
inhibit_all_warnings!

target 'Example-iOS' do

  pod 'BaseValueDecodable', :path => '../'
  
  target 'Example-iOSTests' do
    inherit! :search_paths    
  end
end
